title: Shveta Vasisht
logo: /assets/img/logo.jpg
description: Technical Writer | Software Quality Analyst having 10yrs IT-Software Industry Experience
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
